### ISSUE TITLE
Schema inconsistent with pangolin native outputs

### ISSUE THREAD

**Issue by mkadlof** [michallaz/plepiseq_json#6]
In file `pangolin_lineage.csv` one may find column: `qc_status` which may contain value `fail`. However schema allows only values `['pass', 'warning']` in:

```
data.output.viral_classification_data[0].variant_qc_status
```

We can do one of both:
1. Include value `fail` in schema
2. Translate pangolin `fail` into `warning` in `output.json` file.

Here is an example `EQA23 sample 18` produce output:

```json

"viral_classification_data": [
    {
        "status": "tak",
        "database_name": "Pango",
        "database_version": "4.3.1",
        "program_name": "scorpion",
        "program_version": "0.3.19",
        "variant_name": "Unassigned",
        "variant_qc_status": "fail",
        "sequence_source": "full_genome"
    },   
```

**Comment by michallaz** [comment]
Wydaje mi się że w takiej sytuacji json powinien wyglądać tak:
[
  {
    "status": "blad",
    "database_name": "Pango",
    "error_message": "Analizowana sekwencja nie spełnia kryteriów jakościowych i nie udało się przewidzieć wariantu"
  }
]

Error message jest po polsku zgodnie z wymaganiami epidemiologii.

**Comment by mkadlof** [comment]
We will combine two approaches. If `"variant_qc_status": "fail"`, then we set `"status": "blad"` and we add `"error_message"`. The rest of fields may stay as optional.
