### ISSUE TITLE
Konwencja nazw pól ze ścieżkami do plików

### ISSUE THREAD

**Issue by mkadlof** [michallaz/plepiseq_json#7]
Niektóre pola mają w nazwie `file` inne `path`, a jeszcze inne ani jedno ani drugie. Mając wspólny schemat nazewnictwa łatwiej wyekstrachować w testach pola z plikami do weryfikacji ich istnienia.

przykłady z pliku [full_output_2_viral.json](https://github.com/michallaz/plepiseq_json/blob/main/full_output_2_viral.json)

`"ExecutionDir": "/mnt/sda1/michall/RSV/tmp_sars/",`
`    "dehumanized_fastq_data": [
      "/some/path/forward.fastq.gz",
      "/some/path/reverse.fastq.gz"
    ],`
`"segment_path": "pipeline_wyniki/S3_S5_L001/fastas/NODE1_pilon_pilon_pilon_cov_20.862722668721787.fasta"`
`"reads_quality_histogram_path": "pipeline_wyniki/S3_S5_L001/QC/S3_S5_L001_R1_001_fastqc_reads_quality_histogram.csv",`
`"coverage_histogram_file": "/path/to/a/file",`
`"coinfection_histogram_file": "/some/path",`
`"pdb_path": "/Some/path/to.pdb"`

**Comment by michallaz** [comment]
Resolved with 5d6e7d5 commit.
